[workspace]
members = [
    "sn_node",
    "sn_api",
    "sn_client",
    "sn_cli",
    "sn_updater",
    "sn_comms",
    "sn_fault_detection",
    "sn_cmd_test_utilities",
    "log_cmds_inspector",
    "sn_interface",
    "testnet"
]
