name: Benchmarking

on: [pull_request]

env:
  RUST_BACKTRACE: 1
  SN_NODE_VERSION: "latest"
  RUSTFLAGS: "-D warnings"

jobs:
  build:
    # if: ${{ github.repository_owner == 'maidsafe' }}
    name: Build for benchmarking
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Upload CLI
        uses: actions/upload-artifact@master
        with:
          name: sn_cli
          path: target/release/safe

  benchmark:
    # if: ${{ github.repository_owner == 'maidsafe' }}
    name: Benchmarking ${{ matrix.benchmark }}
    needs: build
    runs-on: ubuntu-latest
    if: false
    strategy:
      matrix:
        benchmark: [ keys, put ]
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p ~/.safe/node
      - name: dl node
        run: wget https://github.com/maidsafe/sn_node/releases/download/${{env.SN_NODE_VERSION}}/sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip
      - run: unzip sn_node-${{env.SN_NODE_VERSION}}-x86_64-unknown-linux-musl.zip -d $HOME/.safe/node

      - name: Setup Safe Cli dir
        run: |
          mkdir -p ~/.safe/cli

      - name: Download CLI
        uses: actions/download-artifact@master
        with:
          name: sn_cli
          path: ./dl

      - run: cp ./dl/safe $HOME/.safe/cli

      - run: ls $HOME/.safe/cli
      - run: echo "$HOME/.safe/cli" >> $GITHUB_PATH
      - run: echo $PATH
      - run: chmod +x $HOME/.safe/cli/safe
      - run: chmod +x $HOME/.safe/node/sn_node

      - name: Setup The Baby
        run : safe node run-baby-fleming

      - name: Benchmark
        run: cargo bench --bench ${{ matrix.benchmark }}
        shell: bash

      - name: Stop the network on fail
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure logs
        if: failure()
        run: tail $HOME/.safe/node/baby-fleming-nodes/*/*.log
