[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Tesnet Starter."
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "testnet"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.0"


[features]
# required to pass on flag to node builds
chaos = []
statemap = []

[[bin]]
path="bin.rs"
name="testnet"



[dependencies]
color-eyre = "~0.6.0"
eyre = "~0.6.5"
clap = { version = "3.0.0", features = ["derive", "env"]}
dirs-next = "2.0.0"
sn_launch_tool = "~0.12.0"
tracing = "~0.1.26"
tracing-core = "~0.1.21"
tracing-subscriber = { version = "~0.3.1", features = ["env-filter", "json"] }

[dependencies.tokio]
version = "1.17.0"
features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync"]
