[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "The Safe Network Tesnet Starter."
documentation = "https://docs.rs/sn_node"
edition = "2021"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_testnet"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_network"
version = "0.1.4"

[features]
# required to pass on flag to node builds
chaos = []
statemap = []
otlp = []
# verify-nodes: performs a last step querying and verifying net knowledge to lanched nodes
verify-nodes = ["prost", "tonic", "xor_name", "tonic-build"]

[[bin]]
path="src/main.rs"
name="testnet"

[dependencies]
color-eyre = "~0.6.0"
eyre = "~0.6.5"
clap = { version = "3.0.0", features = ["derive", "env"]}
dirs-next = "2.0.0"
prost = { version = "~0.11.8", optional = true }
regex = "1.7.1"
tonic = { version = "~0.8.3", optional = true }
tracing = "~0.1.26"
tracing-core = "~0.1.21"
tracing-subscriber = { version = "~0.3.1", features = ["env-filter", "json"] }
xor_name = { version = "~5.0.0", optional = true }
walkdir = "2"

[dependencies.tokio]
version = "1.17.0"
features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync"]

[build-dependencies]
tonic-build = { version = "0.8", optional = true }

[dev-dependencies]
assert_fs = "~1.0"
mockall = "0.11.3"
predicates = "2.0"
