name: Benchmarks

on: pull_request

env:
  CARGO_INCREMENTAL: '0'
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings"
  NODE_COUNT: 15

jobs:
  benchmarks:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Run Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      # TODO: reenable network when we're running a benchmark. At the moment everything is skipped

      # - name: Build launch local network
      #   run: cargo build --release

      # - name: Run testnet
      #   run: ./target/release/testnet
      #   env:
      #     RUST_LOG: "safe_network=trace"

      # - name: Mac install ripgrep
      #   if: matrix.os == 'macos-latest'
      #   run: brew install ripgrep

      # - name: ubuntu install ripgrep
      #   if: matrix.os == 'ubuntu-latest'
      #   run: sudo apt-get -y install ripgrep

      # - name: windows install ripgrep
      #   if: matrix.os == 'windows-latest'
      #   run: choco install ripgrep

      # - name: Wait for all nodes to join
      #   shell: bash
      #   run: ./resources/scripts/wait_for_nodes_to_join.sh
      #   timeout-minutes: 10

      # - name: Bench safe_network
      #   run: cargo bench -p safe_network --features=test-utils

      - name: Stop the network on fail
        if: failure()
        run: safe node killall || true && safe auth stop || true

      - name: Failure logs
        if: failure()
        run: tail $HOME/.safe/node/local-test-network/*/*.log*
