name: version bump

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-20.04
    if: |
      github.repository_owner == 'maidsafe' &&
      !startsWith(github.event.head_commit.message, 'chore(release):')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: stable
          override: true
      - shell: bash
        run: |
          git remote add github "$REPO"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - shell: bash
        run: cargo install cargo-smart-release
      - shell: bash
        run: ./resources/scripts/bump_version.sh
      - name: push version bump and changelog commit
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
          branch: main
      - name: push version tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
          branch: main
          tags: true
