name: Client Changes


on: 
  pull_request:
    paths: 
      - 'src/client/**'
      - 'src/messaging/**'


env:
  # Run all cargo commands with --verbose.
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1
  # Deny all compiler warnings.
  RUSTFLAGS: "-D warnings"

jobs:
  
  # Run test suite.
  client-tests:
    if: "!startsWith(github.event.pull_request.title, 'Automated version bump')"
    name: Client Doc Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2

      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Cache.
      - name: Cargo cache registry, index and build
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cache-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Doc Tests
        shell: bash
        # e2e client tests are run in the separate e2e.yml action
        run: cargo test --release client --doc
